
name: Docker build

on:
  push:
    branches: [ master ]

jobs:
  build-push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push app to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          tags: "ghcr.io/hovoh/twitter-api-service:latest"
          push: true

